fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    logrotate: "https://github.com/yo61/puppet-logrotate.git"
 
# default module layout

  symlinks:
    bussmtp: "#{source_dir}"
